### ISSUE TITLE
PA Review: User Authentication

### ISSUE THREAD

**Issue by joshkohane** [joshkohane/NJTimesCooking#2]
# User Auth
## Functionality
- [x] The main button with logo should link to `/`
- [x] Has working demo login
- [x] Smooth, bug free navigation
### Before Login
- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user
### After Login
- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in
## Style
- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production
## Seeds
- [x] Adequate and appropriate seeds

**Comment by mkayys** [comment]
For styling, you want the navbar to be done for this MVP. 
![Screen Shot 2020-12-10 at 5 09 48 PM](https://user-images.githubusercontent.com/48598856/101848528-8a3e9100-3b0a-11eb-8caa-6c11e180d35e.png)
- continue as demo user --> `cursor: pointer` is missing
- errors on signup page push the text down
![Screen Shot 2020-12-10 at 5 28 17 PM](https://user-images.githubusercontent.com/48598856/101849713-1e115c80-3b0d-11eb-8e70-7c0be0b8e9f9.png) <-- looks like it's cutting it close near the bottom
- lastly maybe a different text for the words on the image and the headers for the session forms (i.e. if possible, no Times)

**Comment by mkayys** [comment]
looks good! One last suggestion for your `login` dropdown. It looks like I have to move my cursor straight down from the gear icon and I am not able to move diagonally to the left to click login.
