### ISSUE TITLE
PA Review: Home Page

### ISSUE THREAD

**Issue by joshkohane** [joshkohane/NJTimesCooking#3]
# Home Page
## Functionality
- [x] The main button with logo should link to `/`
- [x] Nav bar is fixed to the top
- [x] Smooth, bug free navigation
### Before Login
- [x] User can access home page without being logged in
- [x] User can log in from the gear in the upper right hand corner
## Style
- [x] Recipe lists have carousel effect when arrow is clicked
- [x] Recipe cards should link to the appropriate recipe page
- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] Remove Redux logger and all console.log()'s from production
## Seeds
- [x] Adequate and appropriate seeds

**Comment by mkayys** [comment]
- logger is still there but you can remove it at the end
- one very small suggestion is when you click `All Recipes` in the carousel, the scrollbar on the subsequent page is in the middle of the page, not the top
- otherwise, all good to go
